// app/layout.js (or wherever your layout file is located)
import { Inter } from "next/font/google";
import "./globals.css";
import ClientLayout from "../components/ClientLayout"; // Adjust the path as needed

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-stone-950 bg-stone-100 flex`}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}